# Generated by Django 5.0 on 2023-12-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_project_accounts', '0002_remove_address_contact_number_remove_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='ecommerce_project_accounts.address'),
        ),
    ]
