# Generated by Django 5.0 on 2023-12-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_project_transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentoptions',
            name='card',
        ),
        migrations.RemoveField(
            model_name='paymentoptions',
            name='upiID',
        ),
        migrations.AddField(
            model_name='paymentoptions',
            name='cards',
            field=models.ManyToManyField(blank=True, to='ecommerce_project_transactions.card'),
        ),
        migrations.AddField(
            model_name='paymentoptions',
            name='upiIDs',
            field=models.ManyToManyField(blank=True, to='ecommerce_project_transactions.upiid'),
        ),
    ]
