# Generated by Django 5.0 on 2023-12-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_project_accounts', '0005_remove_profile_address1_remove_profile_address2_and_more'),
        ('ecommerce_project_transactions', '0002_remove_paymentoptions_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='order',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('cash_on_delivery', 'Cash on Delivery')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='ecommerce_project_accounts.profile'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('pending', 'Pending')], default='shipped', max_length=20),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
