# Generated by Django 5.0 on 2023-12-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_project_transactions', '0003_remove_ordereditem_order_ordereditem_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
