# Generated by Django 5.0 on 2023-12-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_project_transactions', '0004_cartitem_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce_project_transactions.cartitem'),
        ),
    ]
