# Generated by Django 5.0 on 2023-12-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_project_products', '0004_brand_slug_alter_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
